// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbXBhgVItST1cK1vfovU1boYuqNrHDHLw',
    appId: '1:947263554228:web:32aef7a6b2c875e8a54de1',
    messagingSenderId: '947263554228',
    projectId: 'notes-a2f83',
    authDomain: 'notes-a2f83.firebaseapp.com',
    storageBucket: 'notes-a2f83.firebasestorage.app',
    measurementId: 'G-GWDEZ2LZ2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi_9CPCxmDdWgatTYFcXBpuKTBaWW_haQ',
    appId: '1:947263554228:android:5e78a85989237791a54de1',
    messagingSenderId: '947263554228',
    projectId: 'notes-a2f83',
    storageBucket: 'notes-a2f83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS_3NgvKk93bIYkEbrn8Jy9D1NE1uSh3Q',
    appId: '1:947263554228:ios:77a925fe78532950a54de1',
    messagingSenderId: '947263554228',
    projectId: 'notes-a2f83',
    storageBucket: 'notes-a2f83.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS_3NgvKk93bIYkEbrn8Jy9D1NE1uSh3Q',
    appId: '1:947263554228:ios:77a925fe78532950a54de1',
    messagingSenderId: '947263554228',
    projectId: 'notes-a2f83',
    storageBucket: 'notes-a2f83.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbXBhgVItST1cK1vfovU1boYuqNrHDHLw',
    appId: '1:947263554228:web:5ef645a531307d4ea54de1',
    messagingSenderId: '947263554228',
    projectId: 'notes-a2f83',
    authDomain: 'notes-a2f83.firebaseapp.com',
    storageBucket: 'notes-a2f83.firebasestorage.app',
    measurementId: 'G-N5TQTSBVH0',
  );
}
